// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOSQxccktSLUQfaXR1KlWkC_yLrDkWQ0',
    appId: '1:425761229056:web:a2ec8f26e60bd55c1f8be5',
    messagingSenderId: '425761229056',
    projectId: 'myapp-28e32',
    authDomain: 'myapp-28e32.firebaseapp.com',
    storageBucket: 'myapp-28e32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3aNMHsIBlTyXxrDR49hMgyGcGo0yB4U',
    appId: '1:425761229056:android:ddeedad66b6548d81f8be5',
    messagingSenderId: '425761229056',
    projectId: 'myapp-28e32',
    storageBucket: 'myapp-28e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaLy1HIrkaBuk0ScpRiCLjRf8OHkBdI8',
    appId: '1:425761229056:ios:0418c79c404431701f8be5',
    messagingSenderId: '425761229056',
    projectId: 'myapp-28e32',
    storageBucket: 'myapp-28e32.appspot.com',
    iosClientId: '425761229056-fv9ki599m5s4n330v7s45geru6en043v.apps.googleusercontent.com',
    iosBundleId: 'com.example.pff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYaLy1HIrkaBuk0ScpRiCLjRf8OHkBdI8',
    appId: '1:425761229056:ios:0418c79c404431701f8be5',
    messagingSenderId: '425761229056',
    projectId: 'myapp-28e32',
    storageBucket: 'myapp-28e32.appspot.com',
    iosClientId: '425761229056-fv9ki599m5s4n330v7s45geru6en043v.apps.googleusercontent.com',
    iosBundleId: 'com.example.pff',
  );
}
